[package]
name = "neorg-dirman"
description = "A cross-platform implementation of Dirman in Rust."
version = "0.1.1"
edition = "2021"
license = "GPL-3.0"
license_file = "LICENSE"

[dependencies]
walkdir = "2.4.0"
